spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Land-Management

  datasource:
    url: jdbc:postgresql://localhost:5433/land_management
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

keycloak:
  server-url: http://localhost:8080
  realm: Land-Management
  username: admin_new
  password: admin
  client-id: land-admin-client
  client-secret: HxpzhU5WXiXQs7QioNn7AhxiFGUdXXit

server:
  port: 8081
  logging:
    level:
      root: INFO
      com.UserService.user: INFO
default-role: user






